name: athousandwords
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1
 
dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  loading_animation_widget: ^1.3.0
  riverpod: ^2.6.1
  firebase_messaging: ^15.2.8
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  google_sign_in: ^6.2.2
  go_router: ^15.1.2
  rxdart: ^0.28.0
  intl: ^0.20.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  flutter_svg: ^2.1.0
  timeago: ^3.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  freezed: ^2.4.5
  build_runner: ^2.4.8
  analyzer: ^6.4.1
  analyzer_plugin: ^0.11.2
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets: 
    - assets/images/
  
    # Declare custom fonts
  fonts:
    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather/Merriweather-VariableFont_opsz,wdth,wght.ttf
        - asset: assets/fonts/Merriweather/Merriweather-Italic-VariableFont_opsz,wdth,wght.ttf
          style: italic